### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by mootw** [ibrierley/flutter_map_vector_tiles#10]
Currently there is a ram-cache (where tiles are stored while app is running). We should find a way to make tile data interface like the leaflet image tiles so they can be cached using an external solution between restarts.

**Comment by ibrierley** [comment]
Sounds good. Side issue, but just something that may be related, I just want to check any backup tiles get cleared out..or we leave them in cache, or whatever, but not cause issues with too many tiles in use or whatever.

**Comment by ibrierley** [comment]
Have swapped out http.get for flutter_cache_manager. Just wondering if there should be some retry facility for URLs, but I also feel like it's not quite as essential for a retry, as it will try and use a backup vector tile if there is one available (although that's not as much use when panning and hitting new tiles).

Will close, but happy to reopen and ponder best policy.
